# Generated by Django 4.2.5 on 2023-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfiles',
            name='token',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedfiles',
            name='file',
            field=models.FileField(upload_to='shared_file/'),
        ),
    ]
