# Generated by Django 4.2.5 on 2023-10-03 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sharedfiles_token_alter_sharedfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfiles',
            name='shared_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
